### ISSUE TITLE
LibLog performance

### ISSUE THREAD

**Issue by roji** [damianh/LibLog#129]
Following discussion in https://github.com/npgsql/npgsql/issues/1438, I've whipped up [a minimal benchmark with BenchmarkDotNet](https://github.com/roji/LibLogBenchmarks) that compares raw NLog logging to LibLog+NLog, with a null target. The idea is to compare performance when logging to an enabled and a disabled loglevel (results at the bottom) - feel free to look at my scenarios.

As always with performance, whether the results are acceptable or not is going to depend on the consuming application. However, 16us for a single logging call seems like a lot. A likely culprit is the stack frame walk discussed in #97. In addition, while the use of dynamic makes the code elegant, it likely adds another unnecessary performance hit vs. using only reflection.

Again, I'm not sure what the performance goals of this library is, so you might choose to disregard this entirely.

``` ini

BenchmarkDotNet=v0.10.1, OS=Microsoft Windows NT 6.2.9200.0
Processor=Intel(R) Core(TM) i7-6700HQ CPU 2.60GHz, ProcessorCount=8
Frequency=2531248 Hz, Resolution=395.0620 ns, Timer=TSC
  [Host]     : Clr 4.0.30319.42000, 32bit LegacyJIT-v4.6.1586.0
  DefaultJob : Clr 4.0.30319.42000, 32bit LegacyJIT-v4.6.1586.0


```
 Method | IsDisabled |           Mean |      StdDev | Scaled | Scaled-StdDev |  Gen 0 | Allocated |
------- |----------- |--------------- |------------ |------- |-------------- |------- |---------- |
   **NLog** |      **False** |    **193.1667 ns** |   **1.9550 ns** |   **1.00** |          **0.00** | **0.0386** |     **160 B** |
 LibLog |      False | 16,002.9138 ns | 177.6954 ns |  82.85 |          1.20 | 0.4232 |   3.87 kB |
   **NLog** |       **True** |      **2.3487 ns** |   **0.0220 ns** |   **1.00** |          **0.00** |      **-** |       **0 B** |
 LibLog |       True |     52.7087 ns |   0.6893 ns |  22.44 |          0.35 | 0.0135 |      52 B |

**Comment by roji** [comment]
One additional comment...

Even with the removal of the stack frame stuff (which probably is the main culprit behind this bad performance) and dynamic, there are some tricks/best practices about dynamically accessing types in an efficient way. I suggest you look at [Matt Warren's excellent article about this](http://mattwarren.org/2016/12/14/Why-is-Reflection-slow/).

Basically doing this whole thing right from a performance perspective would enable lots more consumers to use LibLog.

**Comment by caverna** [comment]
May I ask you to include async wrapper too (even using a null target)?
Because I'm using liblog in my serial application and I was having sincronization troubles until I set all my targets with async wrapper...

**Comment by roji** [comment]
@caverna, are you referring to NLog's async wrapper? If so I'm not sure what relevance that has here, the point of these benchmarks is to measure the additional overhead of LibLog over direct Npgsql usage, and not various different setups within NLog itself...

(regardless, you can always fork my repo and add whatever tests you want)

**Comment by caverna** [comment]
I did download your code and you're right, it doesn't make any difference...
Thanks for the tips!

**Comment by damianh** [comment]
Thanks for the benchmark figures @roji :)

In the coming weeks, around VS2017 RTM when I'll be preparing for NetStandard, I will roll this in at same time.

**Comment by roji** [comment]
@damianh, I've received other complaints from Npgsql users about the added dependencies because of the use of Microsoft.Extensions.Logging, and am considering moving away from it. If I end up doing so, I would be happy to switch to LibLog instead, but the lack of netstandard support and the performance issues are blocking for me.

Would you accept PRs from me on both these issues? VS2017 RTMs in 4 days, so it seems like a good time to work on netstandard. Regarding the performance issues, I can replace the expensive dynamic usage with much more optimized delegates as detailed in the article linked to above.

So the question is basically if you would be willing to (quickly) review some PRs if I get to work on thngs :)

**Comment by damianh** [comment]
Hi, @roji lack of netstardard support is blocking me too. I _will_ be sorting this out this week. A PR to replace the expensive dynamic usage would certainly be appreciated :)

**Comment by damianh** [comment]
NetStandard work is in progress. Having great fun with getting ContentFiles working, not.

**Comment by john2014** [comment]
Related pull request for .Net standard https://github.com/damianh/LibLog/pull/125

Maybe roji can help with this?

**Comment by seancostigan** [comment]
Just wanted to see plans were in the works to address the perf issues that @roji documented. We are evaluating this library at my org and we have some (relatively minor) concerns about the performance. Thanks.

**Comment by megakid** [comment]
Since this could become a blocker for us using this library (great idea), I had a quick look at this, primarily from the NLog provider angle - given the similarities, I suspect log4net will be similar.  My findings are below.

I believe the `dynamic` use can be optimized fairly aggressively so I will ignore this for now.

The big performance penalty originates from `StackTrace` use for each enabled log call.  This done to correctly implement the NLog wrapper behaviour (see https://github.com/NLog/NLog/tree/master/examples/ExtendingLoggers).  This provided type is used to enable correct `${callsite}` output when used in NLog target templates.  NLog only generates and attaches a stack trace to the log entry if one or more of it's targets requires callsite information (see https://github.com/NLog/NLog/blob/master/src/NLog/LoggerImpl.cs#L66).  In an ideal world we could use the same mechanism to evaluate the need to look up this wrapper type but this feels like NLog internals and probably should be avoided.  Therefore, I looked at various options to optimize this process.

1. Ensure there is only one public type that can be used within LibLog - this means the stack frame could be cached up front in a field when the logger was created.  We can avoid inlining method complications by using `[MethodImpl(MethodImplOptions.NoInlining)]` on any methods.  For example, if we make all `LogExtensions` methods `MethodImplOptions.NoInlining` then we have partially solved the issue and could assume that the NLog wrapper type is always `LogExtensions` - only exception here being `LoggerExecutionWrapper` but how often will this be used?  Might be other considerations here.
2. Being unable to use the same mechanism as NLog does to lazily look up stack traces, we could add configuration to LibLog to enable stack frame look ups optionally.  If you add `${callsite}` to your target template then you need to enable this lookup in LibLog as well.  This option is the easiest but not very easy and will cause surprise results if people forget to change it (which they will).
3. use `[CallerFilePath]` and `[CallerLineNumber]` and flow that down into the `ILog` interface so we can cache each call site - create an entry in a dictionary for each call site and cache the wrapper type associated with that call site (using the current stack trace traversal technique).  Each call site has a warm up cost and memory overhead could be reasonably large but removes any stack trace generation from the hot path when warm.

I believe another potential performance issue that is ripe for optimization is the `SimulateStructuredLogging` method but that's for another day.

**Comment by damianh** [comment]
Good feedback all.

Going to tackle this for `v5.0.0` for NetStandard 2.0 release timeframe.

**Comment by llehn** [comment]
I'm struck by the slowness. WampSharp uses LibLog - and in my case spending 90% of the time there (with serilog), with disabled loglevel...

Maybe there should be a word of warning for potential used: LibLog may be fine for an application, but not suitable for libraries/frameworks, i.e. all cases when then direct users of LibLog can't predict the scenario in which LibLog will actually be used.

**Comment by megakid** [comment]
I recently fixed up a local copy to use some faster code paths, especially for NLog but also some enhancements in the serilog provider.  I can push a PR if wanted.

**Comment by llehn** [comment]
That would be good. I'd take that and try to improve Serilog provider as well as I can. Maybe we can get this improved faster then.

**Comment by llehn** [comment]
In my case (using WampSharp) the code in the PR improves perf by factor of 10.

**Comment by megakid** [comment]
Working on a PR now but here's what it looks like currently, mainly focusing on NLog now.  This has the currently has the caveat that `${callsite}` does not work correctly under RevisedLibLog

```
         Method |                 Layout |           Mean |      StdDev | Scaled | Scaled-StdDev |  Gen 0 | Allocated |
--------------- |----------------------- |--------------- |------------ |------- |-------------- |------- |---------- |
           NLog | ${callsite} ${message} | 17,716.7684 ns | 133.5503 ns |   1.00 |          0.00 | 0.5859 |   5.26 kB |
 OriginalLibLog | ${callsite} ${message} | 33,322.9539 ns | 910.9674 ns |   1.88 |          0.05 | 1.1149 |  10.11 kB |
  RevisedLibLog | ${callsite} ${message} | 20,030.7325 ns | 213.7729 ns |   1.13 |          0.01 | 0.8586 |   6.61 kB |
           NLog |             ${message} |    413.0363 ns |   3.1330 ns |   1.00 |          0.00 | 0.0609 |     368 B |
 OriginalLibLog |             ${message} | 12,998.1171 ns | 123.3643 ns |  31.47 |          0.37 | 0.2279 |   4.33 kB |
  RevisedLibLog |             ${message} |  1,042.9463 ns |   7.3871 ns |   2.53 |          0.03 | 0.1841 |     976 B |
```
