### ISSUE TITLE
Log4Net provider missing Trace level

### ISSUE THREAD

**Issue by skalinkin** [damianh/LibLog#163]
Trace level treated as Debug. 
https://github.com/damianh/LibLog/blob/b4298bee0d483263add1c60ce2ae1786a225b42c/src/LibLog/LibLog.cs#L1632

Could you add support for Trace level to Log4Net provider.

**Comment by snakefoot** [comment]
Should be simple. Just need to fix the unit-test-constructor. To enable Trace-level:

```
        public Log4NetLogProviderLoggingTests()
        {
            _memoryAppender = new MemoryAppender();
            BasicConfigurator.Configure(_memoryAppender);
            _logProvider = new Log4NetLogProvider();
            _sut = new LoggerExecutionWrapper(new Log4NetLogProvider().GetLogger("Test"));
            var logRepository = LogManager.GetRepository(GetType().Assembly);
            ((log4net.Repository.Hierarchy.Hierarchy)logRepository).Root.Level = Level.All;
        }
```

**Comment by damianh** [comment]
Fixed in https://github.com/damianh/LibLog/commit/2520a7fff675e6795f128a55b9516014659998af . Here LibLog's Trace is mapped to Log4net's ALL. Looking into Log4Net's level class there are many more levels ("Fine" and "Finer"...too many imho). It's not going to be possible to map them all via LibLog's Level.
