### ISSUE TITLE
Support net45 and netstandard2

### ISSUE THREAD

**Issue by austinlparker** [damianh/LibLog#189]
I've got a multi-targeted project that uses the SDK csproj but targets net45 and netstandard2. It looks like the same fix that worked in #167 is viable (`ifdef`'ing out Loupe). Would you accept a PR that made LibLog target `net45;netstandard2`?

**Comment by damianh** [comment]
I have one wee argument against this - .net 4.5 is not supported since [January 2016](https://blogs.msdn.microsoft.com/dotnet/2015/12/09/support-ending-for-the-net-framework-4-4-5-and-4-5-1/) . It probably doesn't matter much, but am I opening myself to any future pain supporting an obsolete TFM?

Cheers

**Comment by austinlparker** [comment]
I don’t think it would be a problem. The Csharp dependency is supported
from net45+, so if you ever took a higher version of that then I presume
you could drop net45 from this as well.

**Comment by damianh** [comment]
Ok, will take this change.
