### ISSUE TITLE
Be notified when SetCurrentLogProvider is called.

### ISSUE THREAD

**Issue by damianh** [damianh/LibLog#38]
The use case is that if you have a component B that uses LibLog but also has child components C & D (possibly ILMerged and internalized) that also use LibLog , if consumer A sets B's CurrentLogProvider, then B may wish to forward that LogProvider to C & D. 

If C & D are using different versions of LibLog, B will need to adapt accordingly.

**Comment by damianh** [comment]
Note, component B will have to adapt the `ILogProvider` to child components C&D's interfaces.

(Oh for structural typing in .net)

**Comment by thirkcircus** [comment]
hi @damianh ,

sorry to resurrect this issue but I'm having trouble knowing how to apply this.

I have exactly the same case you describe in the initial comment - but I'm confused over how componentB can call 
```cs
LogProvider.SetCurrentLogProvider();
```
for componentC, when all componentC's implementations of ILogProvider are internal.
Originally you had public LogProvider implementations but made these internal in #33 so I'm not sure how a consumer can explicitly set a LogProvider for a library it consumes.

# background
My use case is that I've got a library (*componentB*) which explicitly uses serilog to write structured logs.  Further, *componentB* consumes another library *componentC*, which is a kinesis sink for serilog (https://github.com/serilog/serilog-sinks-amazonkinesis).  
Any application/debugging logs within *componentB* or *componentC* I want to be written to the logging framework of the consuming app - which at my workplace is generally nlog.  
I understand that because of the order of LogProviderResolvers, liblog will by default use serilog (which necessarily exists in *componentB*), so I need to explicitly set it to nlog.

# question
I can see how *componentB* should handle the callback to propagate LogProvider configuration to *componentC* but I don't understand how either the consuming application or *componentB* can explicitly set the LogProvider for its dependent library, when all liblog LogProviders are internal...
what I think I want to do is
```cs
LogProvider.SetCurrentLogProvider(new NLogLogProvider());
```

given the two issues (this and #33), I'm sure you've already worked out how to do this - it's just not clear to me from the documentation/code.  If you're able to let me know how, that would be great thanks!

cheers,
justin

**Comment by thirkcircus** [comment]
and fwiw, I was expecting setup (in *componentB*) to be something like this;
```cs
namespace ComponentB { 

  public class SomeClass {

    static readonly Dictionary<Type, Type> LogProviderTypeMap = new Dictionary<Type, Type>
    {
      {typeof (ComponentB.LogProviders.NLogLogProvider),typeof (ComponentC.LogProviders.NLogLogProvider)},
      {typeof (ComponentB.LogProviders.Log4NetLogProvider),typeof (ComponentC.LogProviders.Log4NetLogProvider)}
      // etc
    };

    public static void SetupLogging() {
      ComponentB.LogProvider.OnCurrentLogProviderSet = provider => {
        var componentBLogProviderType = provider.GetType();
        var componentCLogProviderType = LogProviderTypeMap[componentBLogProviderType];
        var componentCLogProvider = (ComponentC.ILogProvider)Activator.CreateInstance(componentCLogProviderType);
        ComponentC.LogProvider.SetCurrentLogProvider(componentCLogProvider);
      };
  }
}
```
