### ISSUE TITLE
JSON Escaping in xxxFormat calls

### ISSUE THREAD

**Issue by leastprivilege** [damianh/LibLog#72]
e.g.

Logger.InfoFormat("{0}\n {1}", "Client validation success", json);

2015-04-21 15:26:54.160 +02:00 [Information] "Client validation success"
 "{
  \"ClientId\": \"client\",
  \"ClientName\": \"Client Credentials Flow Client\",
  \"ClientCredentialType\": \"SharedSecret\"
}"

Does not happen when using `Format` and concat the string manually.

**Comment by damianh** [comment]
It appears that this only happens with Serilog:
![image](https://cloud.githubusercontent.com/assets/57436/7794813/e51a0d04-02ce-11e5-92a2-2f92e73b0e62.png)

NLog:
![image](https://cloud.githubusercontent.com/assets/57436/7794849/255c431e-02cf-11e5-8722-f5309ac7e2df.png)

Log4Net:
![image](https://cloud.githubusercontent.com/assets/57436/7794857/43930ad4-02cf-11e5-8daf-24a78e6c5bb2.png)

In the case of `Serilog`, LibLog is [forwarding the format parameters to Serilog](https://github.com/damianh/LibLog/blob/dev/src/LibLog/LibLog.cs#L1597). For the other loggers, LibLog is [doing the actual formatting](https://github.com/damianh/LibLog/blob/dev/src/LibLog/LibLog.cs#L1879) 

Writing directly to the logger (i.e. **not** using LibLog) give the same output: 
[NLog](https://github.com/damianh/LibLog/blob/issue-72/src/LibLog.Example.NLog/Program.cs#L25)
![image](https://cloud.githubusercontent.com/assets/57436/7795283/cb1ef31a-02d3-11e5-841b-55ef6ec67616.png)

And [Serilog](https://github.com/damianh/LibLog/blob/issue-72/src/LibLog.Example.Serilog/Program.cs#L18-L22):
![image](https://cloud.githubusercontent.com/assets/57436/7795317/18ef44a0-02d4-11e5-8788-e232ede1387e.png)

Note the extra quotes around 'Result' too.

This _looks_ like this it's a Serilog thing and not a LibLog thing.

Pinging the fabulous @nblumhardt for insight :)

**Comment by nblumhardt** [comment]
Serilog's string output format is (questionably ;)) C#-like, so this is expected Serilog output. You can disable it by passing the `l` (literal) format specifier:

```csharp
Logger.InfoFormat("{0}\n {1:l}", "Client validation success", json);
```

**Comment by damianh** [comment]
Thanks @nblumhardt !

**Comment by leastprivilege** [comment]
What's the benefit of being "C# like" here? I don't want to pass anything Serilog specific into LibLog (that would defeat the purpose). Is there a configuration switch to globally disable that behavior?

**Comment by nblumhardt** [comment]
@leastprivilege this is a sink-dependent behaviour, so you could for example switch to https://github.com/serilog/serilog-sinks-literate which doesn't do this (and looks nicer to boot!).

The original driver was to emphasise which parts of the event are structured data; with some experience behind us, alternatives (e.g. using colour like the LiterateConsole sink does) are much nicer.

(It also came of the observation that many, many log format strings include quotes so that the resulting values are easier to grep out, e.g. `"Starting the '{Foo}'"`, so doing it automatically cut some noise from the logging statements.)

It's a decision for Serilog to reconsider in its "2.0" release I think; until then the decision's really in the hands of whoever configures the logger/chooses the sink. Opening a discussion on the Serilog tracker would be interesting if you are keen, though the timeframes are still a bit murky. Cheers!

**Comment by leastprivilege** [comment]
OK - thanks! Got it. 

Like the literate one btw!
